version: '3.8'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - MONGO_URL=mongodb://db:27017/crudapp
    depends_on:
      - db

  db:
    image: mongo:latest
    ports:
      - "27017:27017"
